# Generated by Django 3.0.7 on 2020-07-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcollection',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newcollection',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newcollection',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=9999),
        ),
    ]
